"""Corrected create fn in specialist and helpers file

Revision ID: 60303bcef3a9
Revises: 397c06639c2c
Create Date: 2024-09-23 22:32:48.250169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60303bcef3a9'
down_revision: Union[str, None] = '397c06639c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
