"""Corrected create fn in specialist and helpers file

Revision ID: 6aad39f4f7c4
Revises: a186cd2edb59
Create Date: 2024-09-23 22:53:06.174532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aad39f4f7c4'
down_revision: Union[str, None] = 'a186cd2edb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
