"""Corrected create fn in specialist and helpers file

Revision ID: a186cd2edb59
Revises: 60303bcef3a9
Create Date: 2024-09-23 22:47:23.757821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a186cd2edb59'
down_revision: Union[str, None] = '60303bcef3a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
